fixtures:
  repositories:
    'stdlib':
      repo: http://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: '4.14.0'
    'concat':
      repo: http://github.com/puppetlabs/puppetlabs-concat.git
      ref: '2.2.1'
  symlinks:
    'sendmail': "#{source_dir}"
