fixtures:
  repositories:
    'stdlib':
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.22.0'
    'concat':
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref:  '4.1.0'
    'augeas_core':
      repo: 'https://github.com/puppetlabs/puppetlabs-augeas_core.git'
      ref:  '1.0.3'
      puppet_version: '>= 6.0.0'
    'mailalias_core':
      repo: 'https://github.com/puppetlabs/puppetlabs-mailalias_core.git'
      ref:  '1.0.4'
      puppet_version: '>= 6.0.0'
  symlinks:
    'sendmail': "#{source_dir}"
