fixtures:
  repositories:
    'stdlib':
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: '4.14.0'
    'concat':
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
      ref: '2.2.1'
    'augeas_core':
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      ref: '1.0.3'
    'mailalias_core':
      repo: https://github.com/puppetlabs/puppetlabs-mailalias_core.git
      ref: '1.0.4'
  symlinks:
    'sendmail': "#{source_dir}"
