# CI.yaml --- Check Puppet module

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        puppet_version: [5, 6]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run pdk validate
        uses: puppets-epic-show-theatre/action-pdk-validate@31b5407676af16b690b2b8c54c0767af72fcc34f
        with:
          puppet-version: ${{ matrix.puppet_version }}
